name: build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: build
      run: cmake --build build --config Debug
